name: me
services:
  blog:
    build: ./docker/httpd
    ports:
      - 80
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: 0.05
          memory: 7MB
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80

  load_balancer:
    ports:
      - 8949:80
      - 8080:80
      - 16001:16001
      - 12000-12009:12000-12009
    depends_on:
      - blog
    volumes:
      - /

