name: me
services:
  agent:
    image: ngrinder/agent
    container_name: agent
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - controller
    links:
      - controller

  controller:
    image: ngrinder/controller
    container_name: controller
    ports:
      - 8080:80
      - 16001:16001
      - 12000-12009:12000-12009
    volumes:
      - ~/ngrinder-controller:/opt/ngrinder-controller

